on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+
jobs:
  pubblish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
      - env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          tag="$(git describe --tags --abbrev=0)"
          poetry version "${tag:1}"
          poetry build
          poetry publish
