on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: |
          python -m pip install --upgrade pip
          pip install poetry
      - run: poetry install --no-interaction
      - run: poetry run black --check --diff .
      - run: poetry run isort --check-only .
      - run: poetry run mypy target_avro tests
      - run: poetry run test
